#pragma once
#include <Arduino.h>

const char languages_json[] PROGMEM = R"rawliteral(
{
  "de": {
    "title": "TI CC Flasher",
    "tab_flasher": "FLASHER",
    "tab_debugger": "DEBUGGER",
    "tab_log": "LOG",
    "status_ready": "Bereit",
    "conn_locked": "LOCKED",
    "conn_connected": "Verbunden",
    "conn_error": "Fehler",
    "sec_ctrl": "1. Steuerung",
    "btn_init": "Init / Reset",
    "btn_info": "Info Page lesen",
    "btn_dump": "Flash auslesen",
    "btn_lock": "\uD83D\uDD12 Chip Lock (Protect)",
    "btn_erase": "\u26A0 Chip Löschen (Unlock)",
    "sec_details": "2. Chip Details",
    "lbl_nodata": "Keine Daten.",
    "sec_pinout": "4. Pinbelegung",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Firmware Update",
    "btn_flash": "Flashen",
    "btn_verify": "Verifizieren",
    "sec_log": "Protokoll",
    "btn_clear": "Clear",
    "stat_upload": "Upload läuft...",
    "msg_lock_warn": "ACHTUNG: Lock-Bits setzen?\n\n1. Chip ist danach LESEGESCHÜTZT.\n2. Dumps gehen nicht mehr.\n3. Entsperren nur durch LÖSCHEN.\n\nFortfahren?",
    "msg_erase_warn": "ACHTUNG: Chip wirklich komplett löschen?\n\nAlle Daten gehen verloren! Locked-Chips werden entsperrt.",
    "sec_registers": "Register",
    "sec_gpio": "GPIO Ports",
    "sec_xdata": "XDATA SPEICHER",
    "btn_halt": "HALT (Pause)",
    "btn_resume": "RUN (Start)",
    "btn_step": "STEP (Schritt)",
    "btn_refresh": "Aktualisieren",
    "lbl_len": "Länge:",
    "btn_go": "LOS",
    "msg_wait_debug": "Warte auf Debug-Daten...",
    "msg_loading": "Lade Daten..."
  },
  "en": {
    "title": "TI CC Flasher",
    "tab_flasher": "FLASHER",
    "tab_debugger": "DEBUGGER",
    "tab_log": "LOG",
    "status_ready": "Ready",
    "conn_locked": "LOCKED",
    "conn_connected": "Connected",
    "conn_error": "Error",
    "sec_ctrl": "1. Control",
    "btn_init": "Init / Reset",
    "btn_info": "Read Info Page",
    "btn_dump": "Read Flash (Dump)",
    "btn_lock": "\uD83D\uDD12 Lock Chip (Protect)",
    "btn_erase": "\u26A0 Erase Chip (Unlock)",
    "sec_details": "2. Chip Details",
    "lbl_nodata": "No Data.",
    "sec_pinout": "4. Pinout Reference",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Firmware Update",
    "btn_flash": "Flash",
    "btn_verify": "Verify",
    "sec_log": "Log",
    "btn_clear": "Clear",
    "stat_upload": "Uploading...",
    "msg_lock_warn": "WARNING: Set Lock-Bits?\n\n1. Chip will be READ PROTECTED.\n2. Dumps will fail.\n3. Unlock only via ERASE.\n\nContinue?",
    "msg_erase_warn": "WARNING: Erase entire Chip?\n\nAll data will be lost! Locked chips will be unlocked.",
    "sec_registers": "Registers",
    "sec_gpio": "GPIO Ports",
    "sec_xdata": "XDATA MEMORY",
    "btn_halt": "HALT (Pause)",
    "btn_resume": "RUN (Resume)",
    "btn_step": "STEP (Into)",
    "btn_refresh": "Refresh",
    "lbl_len": "Len:",
    "btn_go": "GO",
    "msg_wait_debug": "Waiting for debug data...",
    "msg_loading": "Loading..."
  },
  "es": {
    "title": "TI CC Flasher",
    "tab_flasher": "GRABADOR",
    "tab_debugger": "DEPURADOR",
    "tab_log": "REGISTRO",
    "status_ready": "Listo",
    "conn_locked": "BLOQUEADO",
    "conn_connected": "Conectado",
    "conn_error": "Error",
    "sec_ctrl": "1. Control",
    "btn_init": "Inic / Reset",
    "btn_info": "Leer Info",
    "btn_dump": "Leer Flash",
    "btn_lock": "\uD83D\uDD12 Bloquear Chip",
    "btn_erase": "\u26A0 Borrar Chip",
    "sec_details": "2. Detalles",
    "lbl_nodata": "Sin datos.",
    "sec_pinout": "4. Pinout",
    "opt_std": "Estándar CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Actualizar Firmware",
    "btn_flash": "Grabar",
    "btn_verify": "Verificar",
    "sec_log": "Registro",
    "btn_clear": "Limpiar",
    "stat_upload": "Subiendo...",
    "msg_lock_warn": "ATENCIÓN: ¿Bloquear Chip?\n\n1. Lectura protegida.\n2. No más volcados.\n3. Desbloqueo solo borrando.\n\n¿Continuar?",
    "msg_erase_warn": "¿Borrar todo el chip?\n\n¡Se perderán todos los datos!",
    "sec_registers": "Registros",
    "sec_gpio": "Puertos GPIO",
    "sec_xdata": "MEMORIA XDATA",
    "btn_halt": "PAUSA (Halt)",
    "btn_resume": "EJECUTAR (Run)",
    "btn_step": "PASO (Step)",
    "btn_refresh": "Actualizar",
    "lbl_len": "Long:",
    "btn_go": "IR",
    "msg_wait_debug": "Esperando datos de depuración...",
    "msg_loading": "Cargando..."
  },
  "fr": {
    "title": "TI CC Flasher",
    "tab_flasher": "PROGRAMMEUR",
    "tab_debugger": "DÉBOGUEUR",
    "tab_log": "JOURNAL",
    "status_ready": "Prêt",
    "conn_locked": "VERROUILLÉ",
    "conn_connected": "Connecté",
    "conn_error": "Erreur",
    "sec_ctrl": "1. Contrôle",
    "btn_init": "Init / Reset",
    "btn_info": "Lire Info",
    "btn_dump": "Lire Flash",
    "btn_lock": "\uD83D\uDD12 Verrouiller Chip",
    "btn_erase": "\u26A0 Effacer Chip",
    "sec_details": "2. Détails",
    "lbl_nodata": "Pas de données.",
    "sec_pinout": "4. Broches (Pinout)",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Mise à jour Firmware",
    "btn_flash": "Flasher",
    "btn_verify": "Vérifier",
    "sec_log": "Journal",
    "btn_clear": "Effacer",
    "stat_upload": "Téléchargement...",
    "msg_lock_warn": "ATTENTION: Verrouiller?\n\n1. Lecture impossible.\n2. Dumps impossibles.\n3. Déverrouillage par effacement.\n\nContinuer?",
    "msg_erase_warn": "Effacer tout le chip?\n\nToutes les données seront perdues!",
    "sec_registers": "Registres",
    "sec_gpio": "Ports GPIO",
    "sec_xdata": "MÉMOIRE XDATA",
    "btn_halt": "HALTE (Pause)",
    "btn_resume": "LANCER (Run)",
    "btn_step": "PAS (Step)",
    "btn_refresh": "Actualiser",
    "lbl_len": "Lon:",
    "btn_go": "GO",
    "msg_wait_debug": "En attente de données...",
    "msg_loading": "Chargement..."
  },
  "it": {
    "title": "TI CC Flasher",
    "tab_flasher": "FLASHER",
    "tab_debugger": "DEBUGGER",
    "tab_log": "LOG",
    "status_ready": "Pronto",
    "conn_locked": "BLOCCATO",
    "conn_connected": "Connesso",
    "conn_error": "Errore",
    "sec_ctrl": "1. Controllo",
    "btn_init": "Iniz / Reset",
    "btn_info": "Leggi Info",
    "btn_dump": "Leggi Flash",
    "btn_lock": "\uD83D\uDD12 Blocca Chip",
    "btn_erase": "\u26A0 Cancella Chip",
    "sec_details": "2. Dettagli",
    "lbl_nodata": "Nessun dato.",
    "sec_pinout": "4. Pinout",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Aggiorna Firmware",
    "btn_flash": "Scrivi",
    "btn_verify": "Verifica",
    "sec_log": "Log",
    "btn_clear": "Pulisci",
    "stat_upload": "Caricamento...",
    "msg_lock_warn": "ATTENZIONE: Bloccare?\n\n1. Protetto da lettura.\n2. Dump impossibili.\n3. Sblocco solo cancellando.\n\nContinuare?",
    "msg_erase_warn": "Cancellare l'intero chip?\n\nTutti i dati andranno persi!",
    "sec_registers": "Registri",
    "sec_gpio": "Porte GPIO",
    "sec_xdata": "MEMORIA XDATA",
    "btn_halt": "ARRESTA (Halt)",
    "btn_resume": "AVVIA (Run)",
    "btn_step": "PASSO (Step)",
    "btn_refresh": "Aggiorna",
    "lbl_len": "Lun:",
    "btn_go": "VAI",
    "msg_wait_debug": "In attesa di dati...",
    "msg_loading": "Caricamento..."
  },
  "pl": {
    "title": "TI CC Flasher",
    "tab_flasher": "PROGRAMATOR",
    "tab_debugger": "DEBUGGER",
    "tab_log": "LOGI",
    "status_ready": "Gotowy",
    "conn_locked": "ZABLOKOWANY",
    "conn_connected": "Połączono",
    "conn_error": "Błąd",
    "sec_ctrl": "1. Sterowanie",
    "btn_init": "Inicjuj / Reset",
    "btn_info": "Czytaj Info",
    "btn_dump": "Czytaj Flash",
    "btn_lock": "\uD83D\uDD12 Zablokuj (Lock)",
    "btn_erase": "\u26A0 Wyczyść (Erase)",
    "sec_details": "2. Szczegóły",
    "lbl_nodata": "Brak danych.",
    "sec_pinout": "4. Wyprowadzenia",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Aktualizacja",
    "btn_flash": "Wgraj",
    "btn_verify": "Weryfikuj",
    "sec_log": "Logi",
    "btn_clear": "Wyczyść",
    "stat_upload": "Wysyłanie...",
    "msg_lock_warn": "UWAGA: Zablokować?\n\n1. Ochrona odczytu.\n2. Brak możliwości zrzutu.\n3. Odblokowanie przez kasowanie.\n\nKontynuować?",
    "msg_erase_warn": "Wyczyścić cały układ?\n\nWszystkie dane zostaną utracone!",
    "sec_registers": "Rejestry",
    "sec_gpio": "Porty GPIO",
    "sec_xdata": "PAMIĘĆ XDATA",
    "btn_halt": "STOP (Halt)",
    "btn_resume": "START (Run)",
    "btn_step": "KROK (Step)",
    "btn_refresh": "Odśwież",
    "lbl_len": "Dł:",
    "btn_go": "IDŹ",
    "msg_wait_debug": "Czekam na dane...",
    "msg_loading": "Ładowanie..."
  },
  "cs": {
    "title": "TI CC Flasher",
    "tab_flasher": "FLASHER",
    "tab_debugger": "DEBUGGER",
    "tab_log": "LOG",
    "status_ready": "Připraven",
    "conn_locked": "UZAMČENO",
    "conn_connected": "Připojeno",
    "conn_error": "Chyba",
    "sec_ctrl": "1. Ovládání",
    "btn_init": "Init / Reset",
    "btn_info": "Číst Info",
    "btn_dump": "Číst Flash",
    "btn_lock": "\uD83D\uDD12 Zamknout Čip",
    "btn_erase": "\u26A0 Vymazat Čip",
    "sec_details": "2. Detaily",
    "lbl_nodata": "Žádná data.",
    "sec_pinout": "4. Zapojení pinů",
    "opt_std": "Standard CC-Debugger",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. Aktualizace FW",
    "btn_flash": "Nahrát",
    "btn_verify": "Ověřit",
    "sec_log": "Protokol",
    "btn_clear": "Smazat",
    "stat_upload": "Nahrávání...",
    "msg_lock_warn": "VAROVÁNÍ: Zamknout?\n\n1. Ochrana proti čtení.\n2. Dump nebude fungovat.\n3. Odemčení pouze smazáním.\n\nPokračovat?",
    "msg_erase_warn": "Vymazat celý čip?\n\nVšechna data budou ztracena!",
    "sec_registers": "Registry",
    "sec_gpio": "GPIO Porty",
    "sec_xdata": "XDATA PAMĚŤ",
    "btn_halt": "STOP (Halt)",
    "btn_resume": "START (Run)",
    "btn_step": "KROK (Step)",
    "btn_refresh": "Obnovit",
    "lbl_len": "Délka:",
    "btn_go": "JÍT",
    "msg_wait_debug": "Čekám na data...",
    "msg_loading": "Načítání..."
  },
  "ja": {
    "title": "TI CC フラッシャー",
    "tab_flasher": "フラッシャー",
    "tab_debugger": "デバッガ",
    "tab_log": "ログ",
    "status_ready": "準備完了",
    "conn_locked": "ロック中",
    "conn_connected": "接続済み",
    "conn_error": "エラー",
    "sec_ctrl": "1. 制御",
    "btn_init": "初期化 / リセット",
    "btn_info": "情報を読み取る",
    "btn_dump": "フラッシュ読取",
    "btn_lock": "\uD83D\uDD12 チップをロック",
    "btn_erase": "\u26A0 チップ消去",
    "sec_details": "2. チップ詳細",
    "lbl_nodata": "データなし",
    "sec_pinout": "4. ピン配置",
    "opt_std": "標準 CCデバッガ",
    "opt_chroma": "Chroma 74 E-Ink",
    "sec_fw": "3. ファームウェア更新",
    "btn_flash": "書き込み",
    "btn_verify": "検証 (Verify)",
    "sec_log": "ログ",
    "btn_clear": "クリア",
    "stat_upload": "アップロード中...",
    "msg_lock_warn": "警告: ロックビットを設定しますか？\n\n1. 読み取り保護されます。\n2. ダンプは不可になります。\n3. 解除は全消去のみ。\n\n続けますか？",
    "msg_erase_warn": "チップ全体を消去しますか？\n\n全データが失われます！",
    "sec_registers": "レジスタ",
    "sec_gpio": "GPIO ポート",
    "sec_xdata": "XDATA メモリ",
    "btn_halt": "停止 (Halt)",
    "btn_resume": "実行 (Run)",
    "btn_step": "ステップ (Step)",
    "btn_refresh": "更新",
    "lbl_len": "長さ:",
    "btn_go": "読込",
    "msg_wait_debug": "デバッグデータ待機中...",
    "msg_loading": "読み込み中..."
  },
  "zh": {
    "title": "TI CC 烧录工具",
    "tab_flasher": "烧录器",
    "tab_debugger": "调试器",
    "tab_log": "日志",
    "status_ready": "就绪",
    "conn_locked": "已锁定",
    "conn_connected": "已连接",
    "conn_error": "错误",
    "sec_ctrl": "1. 控制",
    "btn_init": "初始化 / 复位",
    "btn_info": "读取信息",
    "btn_dump": "读取闪存 (Dump)",
    "btn_lock": "\uD83D\uDD12 锁定芯片",
    "btn_erase": "\u26A0 擦除芯片",
    "sec_details": "2. 芯片详情",
    "lbl_nodata": "无数据",
    "sec_pinout": "4. 引脚定义",
    "opt_std": "标准 CC-Debugger",
    "opt_chroma": "Chroma 74 电子墨水屏",
    "sec_fw": "3. 固件更新",
    "btn_flash": "烧录",
    "btn_verify": "校验",
    "sec_log": "日志",
    "btn_clear": "清除",
    "stat_upload": "上传中...",
    "msg_lock_warn": "警告：设置锁定位？\n\n1. 芯片将被写保护。\n2. 无法读取固件。\n3. 解锁只能通过擦除。\n\n继续？",
    "msg_erase_warn": "擦除整个芯片？\n\n所有数据将丢失！",
    "sec_registers": "寄存器",
    "sec_gpio": "GPIO 端口",
    "sec_xdata": "XDATA 内存",
    "btn_halt": "暂停 (Halt)",
    "btn_resume": "运行 (Run)",
    "btn_step": "单步 (Step)",
    "btn_refresh": "刷新",
    "lbl_len": "长度:",
    "btn_go": "读取",
    "msg_wait_debug": "等待调试数据...",
    "msg_loading": "加载中..."
  }
}
)rawliteral";